services:
  app:
    build: .
    container_name: docker-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://arifbillah360:Qi8KqJVQ2AbyVU@cluster0.vf75phg.mongodb.net/?appName=Cluster0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

